language:
  java

jdk:
  - oraclejdk8

script:
  "./gradlew"

before_script:
  - pip install --user codecov

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "GBWLuXpprgxZ5Zxc48lcS9nNeupAx91HJ6zsoBBgOGg8x7k57ad2BPdPIhFXpAHrXTfmtQyGYWdft4Vxk/trTttm7WMV9N6bQKbc+qFwvlBOF8DsDIyMHoQ/V/NJu9Q4dHxhHl1QGO/EQkp2ARAXQ7n7lqEweSHei6ogLEVSmPIlc/3E11eDWdMmYdlWmm3HwkgAW73Z5vnhaH5nIidxjlpKDaZYRN9fcL3tlnfcDswrQUiN6BoUbOpNyVV7t57ZHhReOfNZdTaxexFX+PDM3OLFzY2mgL9cD/k3jEZBm/4HIJi8O9lNK0pZmAJgONS8bjB1y3d8/TRkH7m5NGHTosZmzN0wKYixiknnUF/cWehNpnS4GzIOChHeHyMpsqWRQE6++KxnjCE5qslosA0nvAYPCK4H9NlybDkdFziga45qht1hgLx7KN0+WKnACxHN328/JuP4kt6dqf2HjEZTkbV3TXvRsvtUKG/gUuqijEVDq+mJatU7FE6s9RlBhxS9zGaOEauqEKF6vpQ2YbWB4l0WPZ9RkSb6KIhCnwNIurnsb5kmJ3+FYXaSQsROOkkOhN3BmGzfhVXx3iww+LRblmKp08DAoTfmnpYuTa6IN6CtpkrqD/yqkffALHx8ZkiMdvwRgHozVU2RFj15KlxHABs1gshOwEWYg/foSM+DhtY="

addons:
  coverity_scan:
    project:
      name: "michaelknigge/afpbox"
      description: "Build submitted via Travis CI"
    notification_email: michael.knigge@gmx.de
    build_command_prepend: "./gradlew clean"
    build_command: "./gradlew"
    branch_pattern: master
